// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);


output   ap_ready;
input  [31:0] data_0_val;
input  [31:0] data_1_val;
input  [31:0] data_2_val;
input  [31:0] data_3_val;
input  [31:0] data_4_val;
input  [31:0] data_5_val;
input  [31:0] data_6_val;
input  [31:0] data_7_val;
input  [31:0] data_8_val;
input  [31:0] data_9_val;
input  [31:0] data_10_val;
input  [31:0] data_11_val;
input  [31:0] data_12_val;
input  [31:0] data_13_val;
input  [31:0] data_14_val;
input  [31:0] data_15_val;
input  [31:0] data_16_val;
input  [31:0] data_17_val;
input  [31:0] data_18_val;
input  [31:0] data_19_val;
input  [31:0] data_20_val;
input  [31:0] data_21_val;
input  [31:0] data_22_val;
input  [31:0] data_23_val;
input  [31:0] data_24_val;
input  [31:0] data_25_val;
input  [31:0] data_26_val;
input  [31:0] data_27_val;
input  [31:0] data_28_val;
input  [31:0] data_29_val;
input  [31:0] data_30_val;
input  [31:0] data_31_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;

wire   [0:0] icmp_ln45_fu_276_p2;
wire   [15:0] trunc_ln_fu_282_p4;
wire   [0:0] icmp_ln45_16_fu_300_p2;
wire   [15:0] trunc_ln46_s_fu_306_p4;
wire   [0:0] icmp_ln45_17_fu_324_p2;
wire   [15:0] trunc_ln46_15_fu_330_p4;
wire   [0:0] icmp_ln45_18_fu_348_p2;
wire   [15:0] trunc_ln46_16_fu_354_p4;
wire   [0:0] icmp_ln45_19_fu_372_p2;
wire   [15:0] trunc_ln46_17_fu_378_p4;
wire   [0:0] icmp_ln45_20_fu_396_p2;
wire   [15:0] trunc_ln46_18_fu_402_p4;
wire   [0:0] icmp_ln45_21_fu_420_p2;
wire   [15:0] trunc_ln46_19_fu_426_p4;
wire   [0:0] icmp_ln45_22_fu_444_p2;
wire   [15:0] trunc_ln46_20_fu_450_p4;
wire   [0:0] icmp_ln45_23_fu_468_p2;
wire   [15:0] trunc_ln46_21_fu_474_p4;
wire   [0:0] icmp_ln45_24_fu_492_p2;
wire   [15:0] trunc_ln46_22_fu_498_p4;
wire   [0:0] icmp_ln45_25_fu_516_p2;
wire   [15:0] trunc_ln46_23_fu_522_p4;
wire   [0:0] icmp_ln45_26_fu_540_p2;
wire   [15:0] trunc_ln46_24_fu_546_p4;
wire   [0:0] icmp_ln45_27_fu_564_p2;
wire   [15:0] trunc_ln46_25_fu_570_p4;
wire   [0:0] icmp_ln45_28_fu_588_p2;
wire   [15:0] trunc_ln46_26_fu_594_p4;
wire   [0:0] icmp_ln45_29_fu_612_p2;
wire   [15:0] trunc_ln46_27_fu_618_p4;
wire   [0:0] icmp_ln45_30_fu_636_p2;
wire   [15:0] trunc_ln46_28_fu_642_p4;
wire   [0:0] icmp_ln45_31_fu_660_p2;
wire   [15:0] trunc_ln46_29_fu_666_p4;
wire   [0:0] icmp_ln45_32_fu_684_p2;
wire   [15:0] trunc_ln46_30_fu_690_p4;
wire   [0:0] icmp_ln45_33_fu_708_p2;
wire   [15:0] trunc_ln46_31_fu_714_p4;
wire   [0:0] icmp_ln45_34_fu_732_p2;
wire   [15:0] trunc_ln46_32_fu_738_p4;
wire   [0:0] icmp_ln45_35_fu_756_p2;
wire   [15:0] trunc_ln46_33_fu_762_p4;
wire   [0:0] icmp_ln45_36_fu_780_p2;
wire   [15:0] trunc_ln46_34_fu_786_p4;
wire   [0:0] icmp_ln45_37_fu_804_p2;
wire   [15:0] trunc_ln46_35_fu_810_p4;
wire   [0:0] icmp_ln45_38_fu_828_p2;
wire   [15:0] trunc_ln46_36_fu_834_p4;
wire   [0:0] icmp_ln45_39_fu_852_p2;
wire   [15:0] trunc_ln46_37_fu_858_p4;
wire   [0:0] icmp_ln45_40_fu_876_p2;
wire   [15:0] trunc_ln46_38_fu_882_p4;
wire   [0:0] icmp_ln45_41_fu_900_p2;
wire   [15:0] trunc_ln46_39_fu_906_p4;
wire   [0:0] icmp_ln45_42_fu_924_p2;
wire   [15:0] trunc_ln46_40_fu_930_p4;
wire   [0:0] icmp_ln45_43_fu_948_p2;
wire   [15:0] trunc_ln46_41_fu_954_p4;
wire   [0:0] icmp_ln45_44_fu_972_p2;
wire   [15:0] trunc_ln46_42_fu_978_p4;
wire   [0:0] icmp_ln45_45_fu_996_p2;
wire   [15:0] trunc_ln46_43_fu_1002_p4;
wire   [0:0] icmp_ln45_46_fu_1020_p2;
wire   [15:0] trunc_ln46_44_fu_1026_p4;
wire   [15:0] select_ln45_fu_292_p3;
wire   [15:0] select_ln45_16_fu_316_p3;
wire   [15:0] select_ln45_17_fu_340_p3;
wire   [15:0] select_ln45_18_fu_364_p3;
wire   [15:0] select_ln45_19_fu_388_p3;
wire   [15:0] select_ln45_20_fu_412_p3;
wire   [15:0] select_ln45_21_fu_436_p3;
wire   [15:0] select_ln45_22_fu_460_p3;
wire   [15:0] select_ln45_23_fu_484_p3;
wire   [15:0] select_ln45_24_fu_508_p3;
wire   [15:0] select_ln45_25_fu_532_p3;
wire   [15:0] select_ln45_26_fu_556_p3;
wire   [15:0] select_ln45_27_fu_580_p3;
wire   [15:0] select_ln45_28_fu_604_p3;
wire   [15:0] select_ln45_29_fu_628_p3;
wire   [15:0] select_ln45_30_fu_652_p3;
wire   [15:0] select_ln45_31_fu_676_p3;
wire   [15:0] select_ln45_32_fu_700_p3;
wire   [15:0] select_ln45_33_fu_724_p3;
wire   [15:0] select_ln45_34_fu_748_p3;
wire   [15:0] select_ln45_35_fu_772_p3;
wire   [15:0] select_ln45_36_fu_796_p3;
wire   [15:0] select_ln45_37_fu_820_p3;
wire   [15:0] select_ln45_38_fu_844_p3;
wire   [15:0] select_ln45_39_fu_868_p3;
wire   [15:0] select_ln45_40_fu_892_p3;
wire   [15:0] select_ln45_41_fu_916_p3;
wire   [15:0] select_ln45_42_fu_940_p3;
wire   [15:0] select_ln45_43_fu_964_p3;
wire   [15:0] select_ln45_44_fu_988_p3;
wire   [15:0] select_ln45_45_fu_1012_p3;
wire   [15:0] select_ln45_46_fu_1036_p3;

assign ap_ready = 1'b1;

assign select_ln45_16_fu_316_p3 = ((icmp_ln45_16_fu_300_p2[0:0] == 1'b1) ? trunc_ln46_s_fu_306_p4 : 16'd0);

assign select_ln45_17_fu_340_p3 = ((icmp_ln45_17_fu_324_p2[0:0] == 1'b1) ? trunc_ln46_15_fu_330_p4 : 16'd0);

assign select_ln45_18_fu_364_p3 = ((icmp_ln45_18_fu_348_p2[0:0] == 1'b1) ? trunc_ln46_16_fu_354_p4 : 16'd0);

assign select_ln45_19_fu_388_p3 = ((icmp_ln45_19_fu_372_p2[0:0] == 1'b1) ? trunc_ln46_17_fu_378_p4 : 16'd0);

assign select_ln45_20_fu_412_p3 = ((icmp_ln45_20_fu_396_p2[0:0] == 1'b1) ? trunc_ln46_18_fu_402_p4 : 16'd0);

assign select_ln45_21_fu_436_p3 = ((icmp_ln45_21_fu_420_p2[0:0] == 1'b1) ? trunc_ln46_19_fu_426_p4 : 16'd0);

assign select_ln45_22_fu_460_p3 = ((icmp_ln45_22_fu_444_p2[0:0] == 1'b1) ? trunc_ln46_20_fu_450_p4 : 16'd0);

assign select_ln45_23_fu_484_p3 = ((icmp_ln45_23_fu_468_p2[0:0] == 1'b1) ? trunc_ln46_21_fu_474_p4 : 16'd0);

assign select_ln45_24_fu_508_p3 = ((icmp_ln45_24_fu_492_p2[0:0] == 1'b1) ? trunc_ln46_22_fu_498_p4 : 16'd0);

assign select_ln45_25_fu_532_p3 = ((icmp_ln45_25_fu_516_p2[0:0] == 1'b1) ? trunc_ln46_23_fu_522_p4 : 16'd0);

assign select_ln45_26_fu_556_p3 = ((icmp_ln45_26_fu_540_p2[0:0] == 1'b1) ? trunc_ln46_24_fu_546_p4 : 16'd0);

assign select_ln45_27_fu_580_p3 = ((icmp_ln45_27_fu_564_p2[0:0] == 1'b1) ? trunc_ln46_25_fu_570_p4 : 16'd0);

assign select_ln45_28_fu_604_p3 = ((icmp_ln45_28_fu_588_p2[0:0] == 1'b1) ? trunc_ln46_26_fu_594_p4 : 16'd0);

assign select_ln45_29_fu_628_p3 = ((icmp_ln45_29_fu_612_p2[0:0] == 1'b1) ? trunc_ln46_27_fu_618_p4 : 16'd0);

assign select_ln45_30_fu_652_p3 = ((icmp_ln45_30_fu_636_p2[0:0] == 1'b1) ? trunc_ln46_28_fu_642_p4 : 16'd0);

assign select_ln45_31_fu_676_p3 = ((icmp_ln45_31_fu_660_p2[0:0] == 1'b1) ? trunc_ln46_29_fu_666_p4 : 16'd0);

assign select_ln45_32_fu_700_p3 = ((icmp_ln45_32_fu_684_p2[0:0] == 1'b1) ? trunc_ln46_30_fu_690_p4 : 16'd0);

assign select_ln45_33_fu_724_p3 = ((icmp_ln45_33_fu_708_p2[0:0] == 1'b1) ? trunc_ln46_31_fu_714_p4 : 16'd0);

assign select_ln45_34_fu_748_p3 = ((icmp_ln45_34_fu_732_p2[0:0] == 1'b1) ? trunc_ln46_32_fu_738_p4 : 16'd0);

assign select_ln45_35_fu_772_p3 = ((icmp_ln45_35_fu_756_p2[0:0] == 1'b1) ? trunc_ln46_33_fu_762_p4 : 16'd0);

assign select_ln45_36_fu_796_p3 = ((icmp_ln45_36_fu_780_p2[0:0] == 1'b1) ? trunc_ln46_34_fu_786_p4 : 16'd0);

assign select_ln45_37_fu_820_p3 = ((icmp_ln45_37_fu_804_p2[0:0] == 1'b1) ? trunc_ln46_35_fu_810_p4 : 16'd0);

assign select_ln45_38_fu_844_p3 = ((icmp_ln45_38_fu_828_p2[0:0] == 1'b1) ? trunc_ln46_36_fu_834_p4 : 16'd0);

assign select_ln45_39_fu_868_p3 = ((icmp_ln45_39_fu_852_p2[0:0] == 1'b1) ? trunc_ln46_37_fu_858_p4 : 16'd0);

assign select_ln45_40_fu_892_p3 = ((icmp_ln45_40_fu_876_p2[0:0] == 1'b1) ? trunc_ln46_38_fu_882_p4 : 16'd0);

assign select_ln45_41_fu_916_p3 = ((icmp_ln45_41_fu_900_p2[0:0] == 1'b1) ? trunc_ln46_39_fu_906_p4 : 16'd0);

assign select_ln45_42_fu_940_p3 = ((icmp_ln45_42_fu_924_p2[0:0] == 1'b1) ? trunc_ln46_40_fu_930_p4 : 16'd0);

assign select_ln45_43_fu_964_p3 = ((icmp_ln45_43_fu_948_p2[0:0] == 1'b1) ? trunc_ln46_41_fu_954_p4 : 16'd0);

assign select_ln45_44_fu_988_p3 = ((icmp_ln45_44_fu_972_p2[0:0] == 1'b1) ? trunc_ln46_42_fu_978_p4 : 16'd0);

assign select_ln45_45_fu_1012_p3 = ((icmp_ln45_45_fu_996_p2[0:0] == 1'b1) ? trunc_ln46_43_fu_1002_p4 : 16'd0);

assign select_ln45_46_fu_1036_p3 = ((icmp_ln45_46_fu_1020_p2[0:0] == 1'b1) ? trunc_ln46_44_fu_1026_p4 : 16'd0);

assign select_ln45_fu_292_p3 = ((icmp_ln45_fu_276_p2[0:0] == 1'b1) ? trunc_ln_fu_282_p4 : 16'd0);

assign trunc_ln46_15_fu_330_p4 = {{data_2_val[19:4]}};

assign trunc_ln46_16_fu_354_p4 = {{data_3_val[19:4]}};

assign trunc_ln46_17_fu_378_p4 = {{data_4_val[19:4]}};

assign trunc_ln46_18_fu_402_p4 = {{data_5_val[19:4]}};

assign trunc_ln46_19_fu_426_p4 = {{data_6_val[19:4]}};

assign trunc_ln46_20_fu_450_p4 = {{data_7_val[19:4]}};

assign trunc_ln46_21_fu_474_p4 = {{data_8_val[19:4]}};

assign trunc_ln46_22_fu_498_p4 = {{data_9_val[19:4]}};

assign trunc_ln46_23_fu_522_p4 = {{data_10_val[19:4]}};

assign trunc_ln46_24_fu_546_p4 = {{data_11_val[19:4]}};

assign trunc_ln46_25_fu_570_p4 = {{data_12_val[19:4]}};

assign trunc_ln46_26_fu_594_p4 = {{data_13_val[19:4]}};

assign trunc_ln46_27_fu_618_p4 = {{data_14_val[19:4]}};

assign trunc_ln46_28_fu_642_p4 = {{data_15_val[19:4]}};

assign trunc_ln46_29_fu_666_p4 = {{data_16_val[19:4]}};

assign trunc_ln46_30_fu_690_p4 = {{data_17_val[19:4]}};

assign trunc_ln46_31_fu_714_p4 = {{data_18_val[19:4]}};

assign trunc_ln46_32_fu_738_p4 = {{data_19_val[19:4]}};

assign trunc_ln46_33_fu_762_p4 = {{data_20_val[19:4]}};

assign trunc_ln46_34_fu_786_p4 = {{data_21_val[19:4]}};

assign trunc_ln46_35_fu_810_p4 = {{data_22_val[19:4]}};

assign trunc_ln46_36_fu_834_p4 = {{data_23_val[19:4]}};

assign trunc_ln46_37_fu_858_p4 = {{data_24_val[19:4]}};

assign trunc_ln46_38_fu_882_p4 = {{data_25_val[19:4]}};

assign trunc_ln46_39_fu_906_p4 = {{data_26_val[19:4]}};

assign trunc_ln46_40_fu_930_p4 = {{data_27_val[19:4]}};

assign trunc_ln46_41_fu_954_p4 = {{data_28_val[19:4]}};

assign trunc_ln46_42_fu_978_p4 = {{data_29_val[19:4]}};

assign trunc_ln46_43_fu_1002_p4 = {{data_30_val[19:4]}};

assign trunc_ln46_44_fu_1026_p4 = {{data_31_val[19:4]}};

assign trunc_ln46_s_fu_306_p4 = {{data_1_val[19:4]}};

assign trunc_ln_fu_282_p4 = {{data_0_val[19:4]}};

assign ap_return_0 = select_ln45_fu_292_p3;

assign ap_return_1 = select_ln45_16_fu_316_p3;

assign ap_return_10 = select_ln45_25_fu_532_p3;

assign ap_return_11 = select_ln45_26_fu_556_p3;

assign ap_return_12 = select_ln45_27_fu_580_p3;

assign ap_return_13 = select_ln45_28_fu_604_p3;

assign ap_return_14 = select_ln45_29_fu_628_p3;

assign ap_return_15 = select_ln45_30_fu_652_p3;

assign ap_return_16 = select_ln45_31_fu_676_p3;

assign ap_return_17 = select_ln45_32_fu_700_p3;

assign ap_return_18 = select_ln45_33_fu_724_p3;

assign ap_return_19 = select_ln45_34_fu_748_p3;

assign ap_return_2 = select_ln45_17_fu_340_p3;

assign ap_return_20 = select_ln45_35_fu_772_p3;

assign ap_return_21 = select_ln45_36_fu_796_p3;

assign ap_return_22 = select_ln45_37_fu_820_p3;

assign ap_return_23 = select_ln45_38_fu_844_p3;

assign ap_return_24 = select_ln45_39_fu_868_p3;

assign ap_return_25 = select_ln45_40_fu_892_p3;

assign ap_return_26 = select_ln45_41_fu_916_p3;

assign ap_return_27 = select_ln45_42_fu_940_p3;

assign ap_return_28 = select_ln45_43_fu_964_p3;

assign ap_return_29 = select_ln45_44_fu_988_p3;

assign ap_return_3 = select_ln45_18_fu_364_p3;

assign ap_return_30 = select_ln45_45_fu_1012_p3;

assign ap_return_31 = select_ln45_46_fu_1036_p3;

assign ap_return_4 = select_ln45_19_fu_388_p3;

assign ap_return_5 = select_ln45_20_fu_412_p3;

assign ap_return_6 = select_ln45_21_fu_436_p3;

assign ap_return_7 = select_ln45_22_fu_460_p3;

assign ap_return_8 = select_ln45_23_fu_484_p3;

assign ap_return_9 = select_ln45_24_fu_508_p3;

assign icmp_ln45_16_fu_300_p2 = (($signed(data_1_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_17_fu_324_p2 = (($signed(data_2_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_18_fu_348_p2 = (($signed(data_3_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_19_fu_372_p2 = (($signed(data_4_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_20_fu_396_p2 = (($signed(data_5_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_21_fu_420_p2 = (($signed(data_6_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_22_fu_444_p2 = (($signed(data_7_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_23_fu_468_p2 = (($signed(data_8_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_24_fu_492_p2 = (($signed(data_9_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_25_fu_516_p2 = (($signed(data_10_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_26_fu_540_p2 = (($signed(data_11_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_27_fu_564_p2 = (($signed(data_12_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_28_fu_588_p2 = (($signed(data_13_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_29_fu_612_p2 = (($signed(data_14_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_30_fu_636_p2 = (($signed(data_15_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_31_fu_660_p2 = (($signed(data_16_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_32_fu_684_p2 = (($signed(data_17_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_33_fu_708_p2 = (($signed(data_18_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_34_fu_732_p2 = (($signed(data_19_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_35_fu_756_p2 = (($signed(data_20_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_36_fu_780_p2 = (($signed(data_21_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_37_fu_804_p2 = (($signed(data_22_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_38_fu_828_p2 = (($signed(data_23_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_39_fu_852_p2 = (($signed(data_24_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_40_fu_876_p2 = (($signed(data_25_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_41_fu_900_p2 = (($signed(data_26_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_42_fu_924_p2 = (($signed(data_27_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_43_fu_948_p2 = (($signed(data_28_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_44_fu_972_p2 = (($signed(data_29_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_45_fu_996_p2 = (($signed(data_30_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_46_fu_1020_p2 = (($signed(data_31_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_276_p2 = (($signed(data_0_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s
