-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_154_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_1_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_1_fu_178_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_2_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_2_fu_202_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_3_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_3_fu_226_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_4_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_4_fu_250_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_5_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_5_fu_274_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_6_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_6_fu_298_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_7_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_7_fu_322_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_8_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_8_fu_346_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_9_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_9_fu_370_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_10_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_s_fu_394_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_11_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_10_fu_418_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_12_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_11_fu_442_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_13_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_12_fu_466_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_14_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_13_fu_490_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_15_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_14_fu_514_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_fu_164_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_1_fu_188_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_2_fu_212_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_3_fu_236_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_4_fu_260_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_5_fu_284_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_6_fu_308_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_7_fu_332_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_8_fu_356_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_9_fu_380_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_10_fu_404_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_11_fu_428_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_12_fu_452_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_13_fu_476_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_14_fu_500_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_15_fu_524_p3 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln45_fu_164_p3;
    ap_return_1 <= select_ln45_1_fu_188_p3;
    ap_return_10 <= select_ln45_10_fu_404_p3;
    ap_return_11 <= select_ln45_11_fu_428_p3;
    ap_return_12 <= select_ln45_12_fu_452_p3;
    ap_return_13 <= select_ln45_13_fu_476_p3;
    ap_return_14 <= select_ln45_14_fu_500_p3;
    ap_return_15 <= select_ln45_15_fu_524_p3;
    ap_return_2 <= select_ln45_2_fu_212_p3;
    ap_return_3 <= select_ln45_3_fu_236_p3;
    ap_return_4 <= select_ln45_4_fu_260_p3;
    ap_return_5 <= select_ln45_5_fu_284_p3;
    ap_return_6 <= select_ln45_6_fu_308_p3;
    ap_return_7 <= select_ln45_7_fu_332_p3;
    ap_return_8 <= select_ln45_8_fu_356_p3;
    ap_return_9 <= select_ln45_9_fu_380_p3;
    icmp_ln45_10_fu_388_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_11_fu_412_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_12_fu_436_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_13_fu_460_p2 <= "1" when (signed(data_13_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_14_fu_484_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_15_fu_508_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_1_fu_172_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_2_fu_196_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_3_fu_220_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_4_fu_244_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_5_fu_268_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_6_fu_292_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_7_fu_316_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_8_fu_340_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_9_fu_364_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_fu_148_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv32_0)) else "0";
    select_ln45_10_fu_404_p3 <= 
        trunc_ln46_s_fu_394_p4 when (icmp_ln45_10_fu_388_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_11_fu_428_p3 <= 
        trunc_ln46_10_fu_418_p4 when (icmp_ln45_11_fu_412_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_12_fu_452_p3 <= 
        trunc_ln46_11_fu_442_p4 when (icmp_ln45_12_fu_436_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_13_fu_476_p3 <= 
        trunc_ln46_12_fu_466_p4 when (icmp_ln45_13_fu_460_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_14_fu_500_p3 <= 
        trunc_ln46_13_fu_490_p4 when (icmp_ln45_14_fu_484_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_15_fu_524_p3 <= 
        trunc_ln46_14_fu_514_p4 when (icmp_ln45_15_fu_508_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_1_fu_188_p3 <= 
        trunc_ln46_1_fu_178_p4 when (icmp_ln45_1_fu_172_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_2_fu_212_p3 <= 
        trunc_ln46_2_fu_202_p4 when (icmp_ln45_2_fu_196_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_3_fu_236_p3 <= 
        trunc_ln46_3_fu_226_p4 when (icmp_ln45_3_fu_220_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_4_fu_260_p3 <= 
        trunc_ln46_4_fu_250_p4 when (icmp_ln45_4_fu_244_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_5_fu_284_p3 <= 
        trunc_ln46_5_fu_274_p4 when (icmp_ln45_5_fu_268_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_6_fu_308_p3 <= 
        trunc_ln46_6_fu_298_p4 when (icmp_ln45_6_fu_292_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_7_fu_332_p3 <= 
        trunc_ln46_7_fu_322_p4 when (icmp_ln45_7_fu_316_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_8_fu_356_p3 <= 
        trunc_ln46_8_fu_346_p4 when (icmp_ln45_8_fu_340_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_9_fu_380_p3 <= 
        trunc_ln46_9_fu_370_p4 when (icmp_ln45_9_fu_364_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_fu_164_p3 <= 
        trunc_ln_fu_154_p4 when (icmp_ln45_fu_148_p2(0) = '1') else 
        ap_const_lv16_0;
    trunc_ln46_10_fu_418_p4 <= data_11_val(19 downto 4);
    trunc_ln46_11_fu_442_p4 <= data_12_val(19 downto 4);
    trunc_ln46_12_fu_466_p4 <= data_13_val(19 downto 4);
    trunc_ln46_13_fu_490_p4 <= data_14_val(19 downto 4);
    trunc_ln46_14_fu_514_p4 <= data_15_val(19 downto 4);
    trunc_ln46_1_fu_178_p4 <= data_1_val(19 downto 4);
    trunc_ln46_2_fu_202_p4 <= data_2_val(19 downto 4);
    trunc_ln46_3_fu_226_p4 <= data_3_val(19 downto 4);
    trunc_ln46_4_fu_250_p4 <= data_4_val(19 downto 4);
    trunc_ln46_5_fu_274_p4 <= data_5_val(19 downto 4);
    trunc_ln46_6_fu_298_p4 <= data_6_val(19 downto 4);
    trunc_ln46_7_fu_322_p4 <= data_7_val(19 downto 4);
    trunc_ln46_8_fu_346_p4 <= data_8_val(19 downto 4);
    trunc_ln46_9_fu_370_p4 <= data_9_val(19 downto 4);
    trunc_ln46_s_fu_394_p4 <= data_10_val(19 downto 4);
    trunc_ln_fu_154_p4 <= data_0_val(19 downto 4);
end behav;
