// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_sigmoid_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_sigmoid_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [23:0] data_val;
output  [9:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [9:0] sigmoid_table_address0;
reg    sigmoid_table_ce0;
wire   [9:0] sigmoid_table_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln121_fu_199_p1;
wire    ap_block_pp0_stage0;
wire   [15:0] tmp_fu_79_p4;
wire   [33:0] shl_ln_fu_71_p3;
wire   [7:0] trunc_ln115_fu_99_p1;
wire   [13:0] tmp_1_fu_103_p3;
wire  signed [24:0] sext_ln115_fu_89_p1;
wire   [0:0] icmp_ln115_1_fu_111_p2;
wire   [24:0] add_ln115_fu_117_p2;
wire   [0:0] icmp_ln115_fu_93_p2;
wire   [24:0] select_ln115_fu_123_p3;
wire   [24:0] data_round_fu_131_p3;
wire   [23:0] trunc_ln116_fu_139_p1;
wire   [24:0] index_fu_143_p2;
wire   [0:0] tmp_2_fu_155_p3;
wire   [23:0] add_ln113_fu_149_p2;
wire   [23:0] index_1_fu_163_p3;
wire   [13:0] tmp_3_fu_175_p4;
wire   [0:0] icmp_ln119_fu_185_p2;
wire   [9:0] trunc_ln113_fu_171_p1;
wire   [9:0] index_2_fu_191_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_sigmoid_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_sigmoid_config9_s_sigmoid_tabkb #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sigmoid_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_table_address0),
    .ce0(sigmoid_table_ce0),
    .q0(sigmoid_table_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sigmoid_table_ce0 = 1'b1;
    end else begin
        sigmoid_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln113_fu_149_p2 = (trunc_ln116_fu_139_p1 + 24'd512);

assign add_ln115_fu_117_p2 = ($signed(sext_ln115_fu_89_p1) + $signed(25'd1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = sigmoid_table_q0;

assign data_round_fu_131_p3 = ((icmp_ln115_fu_93_p2[0:0] == 1'b1) ? select_ln115_fu_123_p3 : sext_ln115_fu_89_p1);

assign icmp_ln115_1_fu_111_p2 = ((tmp_1_fu_103_p3 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_93_p2 = (($signed(shl_ln_fu_71_p3) < $signed(34'd17179869169)) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_185_p2 = ((tmp_3_fu_175_p4 != 14'd0) ? 1'b1 : 1'b0);

assign index_1_fu_163_p3 = ((tmp_2_fu_155_p3[0:0] == 1'b1) ? 24'd0 : add_ln113_fu_149_p2);

assign index_2_fu_191_p3 = ((icmp_ln119_fu_185_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln113_fu_171_p1);

assign index_fu_143_p2 = (data_round_fu_131_p3 + 25'd512);

assign select_ln115_fu_123_p3 = ((icmp_ln115_1_fu_111_p2[0:0] == 1'b1) ? sext_ln115_fu_89_p1 : add_ln115_fu_117_p2);

assign sext_ln115_fu_89_p1 = $signed(tmp_fu_79_p4);

assign shl_ln_fu_71_p3 = {{data_val}, {10'd0}};

assign sigmoid_table_address0 = zext_ln121_fu_199_p1;

assign tmp_1_fu_103_p3 = {{trunc_ln115_fu_99_p1}, {6'd0}};

assign tmp_2_fu_155_p3 = index_fu_143_p2[32'd24];

assign tmp_3_fu_175_p4 = {{index_1_fu_163_p3[23:10]}};

assign tmp_fu_79_p4 = {{data_val[23:8]}};

assign trunc_ln113_fu_171_p1 = index_1_fu_163_p3[9:0];

assign trunc_ln115_fu_99_p1 = data_val[7:0];

assign trunc_ln116_fu_139_p1 = data_round_fu_131_p3[23:0];

assign zext_ln121_fu_199_p1 = index_2_fu_191_p3;

endmodule //myproject_sigmoid_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_sigmoid_config9_s
