-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_17_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_18_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_19_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_20_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_21_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_23_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_24_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_26_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_27_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_28_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_29_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_30_val : IN STD_LOGIC_VECTOR (31 downto 0);
    data_31_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_282_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_16_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_s_fu_306_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_17_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_15_fu_330_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_18_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_16_fu_354_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_19_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_17_fu_378_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_20_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_18_fu_402_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_21_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_19_fu_426_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_22_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_20_fu_450_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_23_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_21_fu_474_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_24_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_22_fu_498_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_25_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_23_fu_522_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_26_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_24_fu_546_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_27_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_25_fu_570_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_28_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_26_fu_594_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_29_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_27_fu_618_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_30_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_28_fu_642_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_31_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_29_fu_666_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_32_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_30_fu_690_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_33_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_31_fu_714_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_34_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_32_fu_738_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_35_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_33_fu_762_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_36_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_34_fu_786_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_37_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_35_fu_810_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_38_fu_828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_36_fu_834_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_39_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_37_fu_858_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_40_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_38_fu_882_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_41_fu_900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_39_fu_906_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_42_fu_924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_40_fu_930_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_43_fu_948_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_41_fu_954_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_44_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_42_fu_978_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_45_fu_996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_43_fu_1002_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_46_fu_1020_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_44_fu_1026_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_fu_292_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_16_fu_316_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_17_fu_340_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_18_fu_364_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_19_fu_388_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_20_fu_412_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_21_fu_436_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_22_fu_460_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_23_fu_484_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_24_fu_508_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_25_fu_532_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_26_fu_556_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_27_fu_580_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_28_fu_604_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_29_fu_628_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_30_fu_652_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_31_fu_676_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_32_fu_700_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_33_fu_724_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_34_fu_748_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_35_fu_772_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_36_fu_796_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_37_fu_820_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_38_fu_844_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_39_fu_868_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_40_fu_892_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_41_fu_916_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_42_fu_940_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_43_fu_964_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_44_fu_988_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_45_fu_1012_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_46_fu_1036_p3 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln45_fu_292_p3;
    ap_return_1 <= select_ln45_16_fu_316_p3;
    ap_return_10 <= select_ln45_25_fu_532_p3;
    ap_return_11 <= select_ln45_26_fu_556_p3;
    ap_return_12 <= select_ln45_27_fu_580_p3;
    ap_return_13 <= select_ln45_28_fu_604_p3;
    ap_return_14 <= select_ln45_29_fu_628_p3;
    ap_return_15 <= select_ln45_30_fu_652_p3;
    ap_return_16 <= select_ln45_31_fu_676_p3;
    ap_return_17 <= select_ln45_32_fu_700_p3;
    ap_return_18 <= select_ln45_33_fu_724_p3;
    ap_return_19 <= select_ln45_34_fu_748_p3;
    ap_return_2 <= select_ln45_17_fu_340_p3;
    ap_return_20 <= select_ln45_35_fu_772_p3;
    ap_return_21 <= select_ln45_36_fu_796_p3;
    ap_return_22 <= select_ln45_37_fu_820_p3;
    ap_return_23 <= select_ln45_38_fu_844_p3;
    ap_return_24 <= select_ln45_39_fu_868_p3;
    ap_return_25 <= select_ln45_40_fu_892_p3;
    ap_return_26 <= select_ln45_41_fu_916_p3;
    ap_return_27 <= select_ln45_42_fu_940_p3;
    ap_return_28 <= select_ln45_43_fu_964_p3;
    ap_return_29 <= select_ln45_44_fu_988_p3;
    ap_return_3 <= select_ln45_18_fu_364_p3;
    ap_return_30 <= select_ln45_45_fu_1012_p3;
    ap_return_31 <= select_ln45_46_fu_1036_p3;
    ap_return_4 <= select_ln45_19_fu_388_p3;
    ap_return_5 <= select_ln45_20_fu_412_p3;
    ap_return_6 <= select_ln45_21_fu_436_p3;
    ap_return_7 <= select_ln45_22_fu_460_p3;
    ap_return_8 <= select_ln45_23_fu_484_p3;
    ap_return_9 <= select_ln45_24_fu_508_p3;
    icmp_ln45_16_fu_300_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_17_fu_324_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_18_fu_348_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_19_fu_372_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_20_fu_396_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_21_fu_420_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_22_fu_444_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_23_fu_468_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_24_fu_492_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_25_fu_516_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_26_fu_540_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_27_fu_564_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_28_fu_588_p2 <= "1" when (signed(data_13_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_29_fu_612_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_30_fu_636_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_31_fu_660_p2 <= "1" when (signed(data_16_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_32_fu_684_p2 <= "1" when (signed(data_17_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_33_fu_708_p2 <= "1" when (signed(data_18_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_34_fu_732_p2 <= "1" when (signed(data_19_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_35_fu_756_p2 <= "1" when (signed(data_20_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_36_fu_780_p2 <= "1" when (signed(data_21_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_37_fu_804_p2 <= "1" when (signed(data_22_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_38_fu_828_p2 <= "1" when (signed(data_23_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_39_fu_852_p2 <= "1" when (signed(data_24_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_40_fu_876_p2 <= "1" when (signed(data_25_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_41_fu_900_p2 <= "1" when (signed(data_26_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_42_fu_924_p2 <= "1" when (signed(data_27_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_43_fu_948_p2 <= "1" when (signed(data_28_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_44_fu_972_p2 <= "1" when (signed(data_29_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_45_fu_996_p2 <= "1" when (signed(data_30_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_46_fu_1020_p2 <= "1" when (signed(data_31_val) > signed(ap_const_lv32_0)) else "0";
    icmp_ln45_fu_276_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv32_0)) else "0";
    select_ln45_16_fu_316_p3 <= 
        trunc_ln46_s_fu_306_p4 when (icmp_ln45_16_fu_300_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_17_fu_340_p3 <= 
        trunc_ln46_15_fu_330_p4 when (icmp_ln45_17_fu_324_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_18_fu_364_p3 <= 
        trunc_ln46_16_fu_354_p4 when (icmp_ln45_18_fu_348_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_19_fu_388_p3 <= 
        trunc_ln46_17_fu_378_p4 when (icmp_ln45_19_fu_372_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_20_fu_412_p3 <= 
        trunc_ln46_18_fu_402_p4 when (icmp_ln45_20_fu_396_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_21_fu_436_p3 <= 
        trunc_ln46_19_fu_426_p4 when (icmp_ln45_21_fu_420_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_22_fu_460_p3 <= 
        trunc_ln46_20_fu_450_p4 when (icmp_ln45_22_fu_444_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_23_fu_484_p3 <= 
        trunc_ln46_21_fu_474_p4 when (icmp_ln45_23_fu_468_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_24_fu_508_p3 <= 
        trunc_ln46_22_fu_498_p4 when (icmp_ln45_24_fu_492_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_25_fu_532_p3 <= 
        trunc_ln46_23_fu_522_p4 when (icmp_ln45_25_fu_516_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_26_fu_556_p3 <= 
        trunc_ln46_24_fu_546_p4 when (icmp_ln45_26_fu_540_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_27_fu_580_p3 <= 
        trunc_ln46_25_fu_570_p4 when (icmp_ln45_27_fu_564_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_28_fu_604_p3 <= 
        trunc_ln46_26_fu_594_p4 when (icmp_ln45_28_fu_588_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_29_fu_628_p3 <= 
        trunc_ln46_27_fu_618_p4 when (icmp_ln45_29_fu_612_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_30_fu_652_p3 <= 
        trunc_ln46_28_fu_642_p4 when (icmp_ln45_30_fu_636_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_31_fu_676_p3 <= 
        trunc_ln46_29_fu_666_p4 when (icmp_ln45_31_fu_660_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_32_fu_700_p3 <= 
        trunc_ln46_30_fu_690_p4 when (icmp_ln45_32_fu_684_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_33_fu_724_p3 <= 
        trunc_ln46_31_fu_714_p4 when (icmp_ln45_33_fu_708_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_34_fu_748_p3 <= 
        trunc_ln46_32_fu_738_p4 when (icmp_ln45_34_fu_732_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_35_fu_772_p3 <= 
        trunc_ln46_33_fu_762_p4 when (icmp_ln45_35_fu_756_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_36_fu_796_p3 <= 
        trunc_ln46_34_fu_786_p4 when (icmp_ln45_36_fu_780_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_37_fu_820_p3 <= 
        trunc_ln46_35_fu_810_p4 when (icmp_ln45_37_fu_804_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_38_fu_844_p3 <= 
        trunc_ln46_36_fu_834_p4 when (icmp_ln45_38_fu_828_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_39_fu_868_p3 <= 
        trunc_ln46_37_fu_858_p4 when (icmp_ln45_39_fu_852_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_40_fu_892_p3 <= 
        trunc_ln46_38_fu_882_p4 when (icmp_ln45_40_fu_876_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_41_fu_916_p3 <= 
        trunc_ln46_39_fu_906_p4 when (icmp_ln45_41_fu_900_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_42_fu_940_p3 <= 
        trunc_ln46_40_fu_930_p4 when (icmp_ln45_42_fu_924_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_43_fu_964_p3 <= 
        trunc_ln46_41_fu_954_p4 when (icmp_ln45_43_fu_948_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_44_fu_988_p3 <= 
        trunc_ln46_42_fu_978_p4 when (icmp_ln45_44_fu_972_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_45_fu_1012_p3 <= 
        trunc_ln46_43_fu_1002_p4 when (icmp_ln45_45_fu_996_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_46_fu_1036_p3 <= 
        trunc_ln46_44_fu_1026_p4 when (icmp_ln45_46_fu_1020_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_fu_292_p3 <= 
        trunc_ln_fu_282_p4 when (icmp_ln45_fu_276_p2(0) = '1') else 
        ap_const_lv16_0;
    trunc_ln46_15_fu_330_p4 <= data_2_val(19 downto 4);
    trunc_ln46_16_fu_354_p4 <= data_3_val(19 downto 4);
    trunc_ln46_17_fu_378_p4 <= data_4_val(19 downto 4);
    trunc_ln46_18_fu_402_p4 <= data_5_val(19 downto 4);
    trunc_ln46_19_fu_426_p4 <= data_6_val(19 downto 4);
    trunc_ln46_20_fu_450_p4 <= data_7_val(19 downto 4);
    trunc_ln46_21_fu_474_p4 <= data_8_val(19 downto 4);
    trunc_ln46_22_fu_498_p4 <= data_9_val(19 downto 4);
    trunc_ln46_23_fu_522_p4 <= data_10_val(19 downto 4);
    trunc_ln46_24_fu_546_p4 <= data_11_val(19 downto 4);
    trunc_ln46_25_fu_570_p4 <= data_12_val(19 downto 4);
    trunc_ln46_26_fu_594_p4 <= data_13_val(19 downto 4);
    trunc_ln46_27_fu_618_p4 <= data_14_val(19 downto 4);
    trunc_ln46_28_fu_642_p4 <= data_15_val(19 downto 4);
    trunc_ln46_29_fu_666_p4 <= data_16_val(19 downto 4);
    trunc_ln46_30_fu_690_p4 <= data_17_val(19 downto 4);
    trunc_ln46_31_fu_714_p4 <= data_18_val(19 downto 4);
    trunc_ln46_32_fu_738_p4 <= data_19_val(19 downto 4);
    trunc_ln46_33_fu_762_p4 <= data_20_val(19 downto 4);
    trunc_ln46_34_fu_786_p4 <= data_21_val(19 downto 4);
    trunc_ln46_35_fu_810_p4 <= data_22_val(19 downto 4);
    trunc_ln46_36_fu_834_p4 <= data_23_val(19 downto 4);
    trunc_ln46_37_fu_858_p4 <= data_24_val(19 downto 4);
    trunc_ln46_38_fu_882_p4 <= data_25_val(19 downto 4);
    trunc_ln46_39_fu_906_p4 <= data_26_val(19 downto 4);
    trunc_ln46_40_fu_930_p4 <= data_27_val(19 downto 4);
    trunc_ln46_41_fu_954_p4 <= data_28_val(19 downto 4);
    trunc_ln46_42_fu_978_p4 <= data_29_val(19 downto 4);
    trunc_ln46_43_fu_1002_p4 <= data_30_val(19 downto 4);
    trunc_ln46_44_fu_1026_p4 <= data_31_val(19 downto 4);
    trunc_ln46_s_fu_306_p4 <= data_1_val(19 downto 4);
    trunc_ln_fu_282_p4 <= data_0_val(19 downto 4);
end behav;
