// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);


output   ap_ready;
input  [31:0] data_0_val;
input  [31:0] data_1_val;
input  [31:0] data_2_val;
input  [31:0] data_3_val;
input  [31:0] data_4_val;
input  [31:0] data_5_val;
input  [31:0] data_6_val;
input  [31:0] data_7_val;
input  [31:0] data_8_val;
input  [31:0] data_9_val;
input  [31:0] data_10_val;
input  [31:0] data_11_val;
input  [31:0] data_12_val;
input  [31:0] data_13_val;
input  [31:0] data_14_val;
input  [31:0] data_15_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;

wire   [0:0] icmp_ln45_fu_148_p2;
wire   [15:0] trunc_ln_fu_154_p4;
wire   [0:0] icmp_ln45_1_fu_172_p2;
wire   [15:0] trunc_ln46_1_fu_178_p4;
wire   [0:0] icmp_ln45_2_fu_196_p2;
wire   [15:0] trunc_ln46_2_fu_202_p4;
wire   [0:0] icmp_ln45_3_fu_220_p2;
wire   [15:0] trunc_ln46_3_fu_226_p4;
wire   [0:0] icmp_ln45_4_fu_244_p2;
wire   [15:0] trunc_ln46_4_fu_250_p4;
wire   [0:0] icmp_ln45_5_fu_268_p2;
wire   [15:0] trunc_ln46_5_fu_274_p4;
wire   [0:0] icmp_ln45_6_fu_292_p2;
wire   [15:0] trunc_ln46_6_fu_298_p4;
wire   [0:0] icmp_ln45_7_fu_316_p2;
wire   [15:0] trunc_ln46_7_fu_322_p4;
wire   [0:0] icmp_ln45_8_fu_340_p2;
wire   [15:0] trunc_ln46_8_fu_346_p4;
wire   [0:0] icmp_ln45_9_fu_364_p2;
wire   [15:0] trunc_ln46_9_fu_370_p4;
wire   [0:0] icmp_ln45_10_fu_388_p2;
wire   [15:0] trunc_ln46_s_fu_394_p4;
wire   [0:0] icmp_ln45_11_fu_412_p2;
wire   [15:0] trunc_ln46_10_fu_418_p4;
wire   [0:0] icmp_ln45_12_fu_436_p2;
wire   [15:0] trunc_ln46_11_fu_442_p4;
wire   [0:0] icmp_ln45_13_fu_460_p2;
wire   [15:0] trunc_ln46_12_fu_466_p4;
wire   [0:0] icmp_ln45_14_fu_484_p2;
wire   [15:0] trunc_ln46_13_fu_490_p4;
wire   [0:0] icmp_ln45_15_fu_508_p2;
wire   [15:0] trunc_ln46_14_fu_514_p4;
wire   [15:0] select_ln45_fu_164_p3;
wire   [15:0] select_ln45_1_fu_188_p3;
wire   [15:0] select_ln45_2_fu_212_p3;
wire   [15:0] select_ln45_3_fu_236_p3;
wire   [15:0] select_ln45_4_fu_260_p3;
wire   [15:0] select_ln45_5_fu_284_p3;
wire   [15:0] select_ln45_6_fu_308_p3;
wire   [15:0] select_ln45_7_fu_332_p3;
wire   [15:0] select_ln45_8_fu_356_p3;
wire   [15:0] select_ln45_9_fu_380_p3;
wire   [15:0] select_ln45_10_fu_404_p3;
wire   [15:0] select_ln45_11_fu_428_p3;
wire   [15:0] select_ln45_12_fu_452_p3;
wire   [15:0] select_ln45_13_fu_476_p3;
wire   [15:0] select_ln45_14_fu_500_p3;
wire   [15:0] select_ln45_15_fu_524_p3;

assign ap_ready = 1'b1;

assign select_ln45_10_fu_404_p3 = ((icmp_ln45_10_fu_388_p2[0:0] == 1'b1) ? trunc_ln46_s_fu_394_p4 : 16'd0);

assign select_ln45_11_fu_428_p3 = ((icmp_ln45_11_fu_412_p2[0:0] == 1'b1) ? trunc_ln46_10_fu_418_p4 : 16'd0);

assign select_ln45_12_fu_452_p3 = ((icmp_ln45_12_fu_436_p2[0:0] == 1'b1) ? trunc_ln46_11_fu_442_p4 : 16'd0);

assign select_ln45_13_fu_476_p3 = ((icmp_ln45_13_fu_460_p2[0:0] == 1'b1) ? trunc_ln46_12_fu_466_p4 : 16'd0);

assign select_ln45_14_fu_500_p3 = ((icmp_ln45_14_fu_484_p2[0:0] == 1'b1) ? trunc_ln46_13_fu_490_p4 : 16'd0);

assign select_ln45_15_fu_524_p3 = ((icmp_ln45_15_fu_508_p2[0:0] == 1'b1) ? trunc_ln46_14_fu_514_p4 : 16'd0);

assign select_ln45_1_fu_188_p3 = ((icmp_ln45_1_fu_172_p2[0:0] == 1'b1) ? trunc_ln46_1_fu_178_p4 : 16'd0);

assign select_ln45_2_fu_212_p3 = ((icmp_ln45_2_fu_196_p2[0:0] == 1'b1) ? trunc_ln46_2_fu_202_p4 : 16'd0);

assign select_ln45_3_fu_236_p3 = ((icmp_ln45_3_fu_220_p2[0:0] == 1'b1) ? trunc_ln46_3_fu_226_p4 : 16'd0);

assign select_ln45_4_fu_260_p3 = ((icmp_ln45_4_fu_244_p2[0:0] == 1'b1) ? trunc_ln46_4_fu_250_p4 : 16'd0);

assign select_ln45_5_fu_284_p3 = ((icmp_ln45_5_fu_268_p2[0:0] == 1'b1) ? trunc_ln46_5_fu_274_p4 : 16'd0);

assign select_ln45_6_fu_308_p3 = ((icmp_ln45_6_fu_292_p2[0:0] == 1'b1) ? trunc_ln46_6_fu_298_p4 : 16'd0);

assign select_ln45_7_fu_332_p3 = ((icmp_ln45_7_fu_316_p2[0:0] == 1'b1) ? trunc_ln46_7_fu_322_p4 : 16'd0);

assign select_ln45_8_fu_356_p3 = ((icmp_ln45_8_fu_340_p2[0:0] == 1'b1) ? trunc_ln46_8_fu_346_p4 : 16'd0);

assign select_ln45_9_fu_380_p3 = ((icmp_ln45_9_fu_364_p2[0:0] == 1'b1) ? trunc_ln46_9_fu_370_p4 : 16'd0);

assign select_ln45_fu_164_p3 = ((icmp_ln45_fu_148_p2[0:0] == 1'b1) ? trunc_ln_fu_154_p4 : 16'd0);

assign trunc_ln46_10_fu_418_p4 = {{data_11_val[19:4]}};

assign trunc_ln46_11_fu_442_p4 = {{data_12_val[19:4]}};

assign trunc_ln46_12_fu_466_p4 = {{data_13_val[19:4]}};

assign trunc_ln46_13_fu_490_p4 = {{data_14_val[19:4]}};

assign trunc_ln46_14_fu_514_p4 = {{data_15_val[19:4]}};

assign trunc_ln46_1_fu_178_p4 = {{data_1_val[19:4]}};

assign trunc_ln46_2_fu_202_p4 = {{data_2_val[19:4]}};

assign trunc_ln46_3_fu_226_p4 = {{data_3_val[19:4]}};

assign trunc_ln46_4_fu_250_p4 = {{data_4_val[19:4]}};

assign trunc_ln46_5_fu_274_p4 = {{data_5_val[19:4]}};

assign trunc_ln46_6_fu_298_p4 = {{data_6_val[19:4]}};

assign trunc_ln46_7_fu_322_p4 = {{data_7_val[19:4]}};

assign trunc_ln46_8_fu_346_p4 = {{data_8_val[19:4]}};

assign trunc_ln46_9_fu_370_p4 = {{data_9_val[19:4]}};

assign trunc_ln46_s_fu_394_p4 = {{data_10_val[19:4]}};

assign trunc_ln_fu_154_p4 = {{data_0_val[19:4]}};

assign ap_return_0 = select_ln45_fu_164_p3;

assign ap_return_1 = select_ln45_1_fu_188_p3;

assign ap_return_10 = select_ln45_10_fu_404_p3;

assign ap_return_11 = select_ln45_11_fu_428_p3;

assign ap_return_12 = select_ln45_12_fu_452_p3;

assign ap_return_13 = select_ln45_13_fu_476_p3;

assign ap_return_14 = select_ln45_14_fu_500_p3;

assign ap_return_15 = select_ln45_15_fu_524_p3;

assign ap_return_2 = select_ln45_2_fu_212_p3;

assign ap_return_3 = select_ln45_3_fu_236_p3;

assign ap_return_4 = select_ln45_4_fu_260_p3;

assign ap_return_5 = select_ln45_5_fu_284_p3;

assign ap_return_6 = select_ln45_6_fu_308_p3;

assign ap_return_7 = select_ln45_7_fu_332_p3;

assign ap_return_8 = select_ln45_8_fu_356_p3;

assign ap_return_9 = select_ln45_9_fu_380_p3;

assign icmp_ln45_10_fu_388_p2 = (($signed(data_10_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_412_p2 = (($signed(data_11_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_436_p2 = (($signed(data_12_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_460_p2 = (($signed(data_13_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_484_p2 = (($signed(data_14_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_508_p2 = (($signed(data_15_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_172_p2 = (($signed(data_1_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_196_p2 = (($signed(data_2_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_220_p2 = (($signed(data_3_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_244_p2 = (($signed(data_4_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_268_p2 = (($signed(data_5_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_292_p2 = (($signed(data_6_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_316_p2 = (($signed(data_7_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_340_p2 = (($signed(data_8_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_364_p2 = (($signed(data_9_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_148_p2 = (($signed(data_0_val) > $signed(32'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_32_18_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s
