// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_32_18_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        ap_return,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
output  [23:0] ap_return;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [19:0] grp_fu_293_p4;
reg   [19:0] reg_323;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state14;
reg   [18:0] reg_327;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire   [20:0] add_ln58_fu_349_p2;
reg   [20:0] add_ln58_reg_681;
wire    ap_CS_fsm_state2;
wire   [21:0] add_ln58_4801_fu_386_p2;
reg   [21:0] add_ln58_4801_reg_686;
wire    ap_CS_fsm_state4;
wire   [20:0] add_ln58_4802_fu_410_p2;
reg   [20:0] add_ln58_4802_reg_691;
wire    ap_CS_fsm_state6;
wire   [22:0] add_ln58_4805_fu_460_p2;
reg   [22:0] add_ln58_4805_reg_696;
wire    ap_CS_fsm_state8;
reg   [16:0] trunc_ln42_8_reg_701;
wire    ap_CS_fsm_state9;
wire   [20:0] add_ln58_4807_fu_499_p2;
reg   [20:0] add_ln58_4807_reg_706;
wire    ap_CS_fsm_state11;
wire   [19:0] add_ln58_4809_fu_533_p2;
reg   [19:0] add_ln58_4809_reg_711;
wire    ap_CS_fsm_state13;
reg   [15:0] ap_port_reg_data_1_val;
reg   [15:0] ap_port_reg_data_2_val;
reg   [15:0] ap_port_reg_data_3_val;
reg   [15:0] ap_port_reg_data_4_val;
reg   [15:0] ap_port_reg_data_5_val;
reg   [15:0] ap_port_reg_data_6_val;
reg   [15:0] ap_port_reg_data_7_val;
reg   [15:0] ap_port_reg_data_8_val;
reg   [15:0] ap_port_reg_data_9_val;
reg   [15:0] ap_port_reg_data_10_val;
reg   [15:0] ap_port_reg_data_11_val;
reg   [15:0] ap_port_reg_data_12_val;
reg   [15:0] ap_port_reg_data_13_val;
reg   [15:0] ap_port_reg_data_14_val;
reg   [15:0] ap_port_reg_data_15_val;
wire    ap_CS_fsm_state15;
reg  signed [15:0] grp_fu_210_p0;
wire  signed [29:0] sext_ln70_fu_331_p1;
wire  signed [27:0] sext_ln70_465_fu_340_p1;
wire  signed [29:0] sext_ln70_466_fu_355_p1;
wire  signed [27:0] sext_ln70_467_fu_364_p1;
wire  signed [28:0] sext_ln70_468_fu_392_p1;
wire  signed [29:0] sext_ln70_469_fu_401_p1;
wire  signed [29:0] sext_ln70_470_fu_416_p1;
wire  signed [29:0] sext_ln70_471_fu_425_p1;
wire  signed [26:0] sext_ln70_472_fu_466_p1;
wire  signed [28:0] sext_ln70_473_fu_481_p1;
wire  signed [29:0] sext_ln70_474_fu_490_p1;
wire  signed [28:0] sext_ln70_475_fu_505_p1;
wire  signed [24:0] sext_ln70_476_fu_514_p1;
wire  signed [29:0] sext_ln70_477_fu_539_p1;
wire  signed [25:0] sext_ln70_478_fu_595_p1;
reg  signed [14:0] grp_fu_210_p1;
wire   [29:0] grp_fu_210_p2;
wire   [27:0] grp_fu_303_p1;
wire   [28:0] grp_fu_313_p1;
wire   [17:0] grp_fu_303_p4;
wire  signed [20:0] sext_ln70_479_fu_336_p1;
wire  signed [20:0] sext_ln70_480_fu_345_p1;
wire  signed [20:0] sext_ln70_481_fu_360_p1;
wire  signed [20:0] sext_ln70_482_fu_369_p1;
wire   [20:0] add_ln58_4800_fu_376_p2;
wire  signed [21:0] sext_ln58_3218_fu_382_p1;
wire  signed [21:0] sext_ln58_3217_fu_373_p1;
wire  signed [20:0] sext_ln70_483_fu_397_p1;
wire  signed [20:0] sext_ln70_484_fu_406_p1;
wire  signed [20:0] sext_ln70_485_fu_421_p1;
wire  signed [20:0] sext_ln70_486_fu_430_p1;
wire   [20:0] add_ln58_4803_fu_440_p2;
wire  signed [21:0] sext_ln58_3221_fu_446_p1;
wire  signed [21:0] sext_ln58_3220_fu_437_p1;
wire   [21:0] add_ln58_4804_fu_450_p2;
wire  signed [22:0] sext_ln58_3222_fu_456_p1;
wire  signed [22:0] sext_ln58_3219_fu_434_p1;
wire   [26:0] trunc_ln42_8_fu_471_p1;
wire  signed [20:0] sext_ln70_489_fu_486_p1;
wire  signed [20:0] sext_ln70_490_fu_495_p1;
wire   [24:0] trunc_ln42_12_fu_519_p1;
wire   [14:0] trunc_ln42_12_fu_519_p4;
wire  signed [19:0] sext_ln70_491_fu_510_p1;
wire  signed [19:0] sext_ln70_492_fu_529_p1;
wire   [27:0] shl_ln_fu_544_p3;
wire   [21:0] shl_ln73_s_fu_556_p3;
wire  signed [28:0] sext_ln73_fu_552_p1;
wire  signed [28:0] sext_ln73_267_fu_564_p1;
wire   [28:0] add_ln73_fu_568_p2;
wire   [18:0] trunc_ln42_7_fu_574_p4;
wire   [25:0] trunc_ln42_14_fu_600_p1;
wire   [15:0] trunc_ln42_14_fu_600_p4;
wire  signed [19:0] sext_ln70_487_fu_584_p1;
wire  signed [19:0] sext_ln70_488_fu_588_p1;
wire   [19:0] add_ln58_4806_fu_617_p2;
wire  signed [21:0] sext_ln58_3225_fu_627_p1;
wire  signed [21:0] sext_ln58_3224_fu_623_p1;
wire  signed [16:0] sext_ln58_fu_610_p1;
wire   [16:0] add_ln58_4810_fu_639_p2;
wire  signed [20:0] sext_ln58_3227_fu_645_p1;
wire  signed [20:0] sext_ln70_493_fu_591_p1;
wire   [20:0] add_ln58_4811_fu_649_p2;
wire  signed [20:0] sext_ln58_3226_fu_636_p1;
wire   [20:0] add_ln58_4812_fu_655_p2;
wire  signed [21:0] sext_ln58_3228_fu_661_p1;
wire   [21:0] add_ln58_4808_fu_630_p2;
wire   [21:0] add_ln58_4813_fu_665_p2;
wire  signed [23:0] sext_ln58_3229_fu_671_p1;
wire  signed [23:0] sext_ln58_3223_fu_614_p1;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
end

myproject_mul_16s_15s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_16s_15s_30_1_1_U444(
    .din0(grp_fu_210_p0),
    .din1(grp_fu_210_p1),
    .dout(grp_fu_210_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln58_4801_reg_686 <= add_ln58_4801_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln58_4802_reg_691 <= add_ln58_4802_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln58_4805_reg_696 <= add_ln58_4805_fu_460_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln58_4807_reg_706 <= add_ln58_4807_fu_499_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln58_4809_reg_711 <= add_ln58_4809_fu_533_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln58_reg_681 <= add_ln58_fu_349_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_port_reg_data_10_val <= data_10_val;
        ap_port_reg_data_11_val <= data_11_val;
        ap_port_reg_data_12_val <= data_12_val;
        ap_port_reg_data_13_val <= data_13_val;
        ap_port_reg_data_14_val <= data_14_val;
        ap_port_reg_data_15_val <= data_15_val;
        ap_port_reg_data_1_val <= data_1_val;
        ap_port_reg_data_2_val <= data_2_val;
        ap_port_reg_data_3_val <= data_3_val;
        ap_port_reg_data_4_val <= data_4_val;
        ap_port_reg_data_5_val <= data_5_val;
        ap_port_reg_data_6_val <= data_6_val;
        ap_port_reg_data_7_val <= data_7_val;
        ap_port_reg_data_8_val <= data_8_val;
        ap_port_reg_data_9_val <= data_9_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state1))) begin
        reg_323 <= {{grp_fu_210_p2[29:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_327 <= {{grp_fu_313_p1[28:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        trunc_ln42_8_reg_701 <= {{trunc_ln42_8_fu_471_p1[26:10]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_ce) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state15)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_210_p0 = sext_ln70_478_fu_595_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_210_p0 = sext_ln70_477_fu_539_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_210_p0 = sext_ln70_476_fu_514_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_210_p0 = sext_ln70_475_fu_505_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_210_p0 = sext_ln70_474_fu_490_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_210_p0 = sext_ln70_473_fu_481_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_210_p0 = sext_ln70_472_fu_466_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_210_p0 = sext_ln70_471_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_210_p0 = sext_ln70_470_fu_416_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_210_p0 = sext_ln70_469_fu_401_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_210_p0 = sext_ln70_468_fu_392_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_210_p0 = sext_ln70_467_fu_364_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_210_p0 = sext_ln70_466_fu_355_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_210_p0 = sext_ln70_465_fu_340_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_210_p0 = sext_ln70_fu_331_p1;
    end else begin
        grp_fu_210_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_210_p1 = 26'd67108410;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_210_p1 = 30'd6500;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_210_p1 = 25'd33554301;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_210_p1 = 29'd3027;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_210_p1 = 30'd7207;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_210_p1 = 29'd536867769;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_210_p1 = 27'd134216976;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_210_p1 = 30'd4730;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_210_p1 = 30'd1073734594;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_210_p1 = 30'd4317;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_210_p1 = 29'd536867870;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_210_p1 = 28'd1233;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_210_p1 = 30'd6210;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_210_p1 = 28'd1076;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_210_p1 = 30'd1073735346;
    end else begin
        grp_fu_210_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (1'b1 == ap_ce))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_4800_fu_376_p2 = ($signed(sext_ln70_481_fu_360_p1) + $signed(sext_ln70_482_fu_369_p1));

assign add_ln58_4801_fu_386_p2 = ($signed(sext_ln58_3218_fu_382_p1) + $signed(sext_ln58_3217_fu_373_p1));

assign add_ln58_4802_fu_410_p2 = ($signed(sext_ln70_483_fu_397_p1) + $signed(sext_ln70_484_fu_406_p1));

assign add_ln58_4803_fu_440_p2 = ($signed(sext_ln70_485_fu_421_p1) + $signed(sext_ln70_486_fu_430_p1));

assign add_ln58_4804_fu_450_p2 = ($signed(sext_ln58_3221_fu_446_p1) + $signed(sext_ln58_3220_fu_437_p1));

assign add_ln58_4805_fu_460_p2 = ($signed(sext_ln58_3222_fu_456_p1) + $signed(sext_ln58_3219_fu_434_p1));

assign add_ln58_4806_fu_617_p2 = ($signed(sext_ln70_487_fu_584_p1) + $signed(sext_ln70_488_fu_588_p1));

assign add_ln58_4807_fu_499_p2 = ($signed(sext_ln70_489_fu_486_p1) + $signed(sext_ln70_490_fu_495_p1));

assign add_ln58_4808_fu_630_p2 = ($signed(sext_ln58_3225_fu_627_p1) + $signed(sext_ln58_3224_fu_623_p1));

assign add_ln58_4809_fu_533_p2 = ($signed(sext_ln70_491_fu_510_p1) + $signed(sext_ln70_492_fu_529_p1));

assign add_ln58_4810_fu_639_p2 = ($signed(sext_ln58_fu_610_p1) + $signed(17'd24));

assign add_ln58_4811_fu_649_p2 = ($signed(sext_ln58_3227_fu_645_p1) + $signed(sext_ln70_493_fu_591_p1));

assign add_ln58_4812_fu_655_p2 = ($signed(add_ln58_4811_fu_649_p2) + $signed(sext_ln58_3226_fu_636_p1));

assign add_ln58_4813_fu_665_p2 = ($signed(sext_ln58_3228_fu_661_p1) + $signed(add_ln58_4808_fu_630_p2));

assign add_ln58_fu_349_p2 = ($signed(sext_ln70_479_fu_336_p1) + $signed(sext_ln70_480_fu_345_p1));

assign add_ln73_fu_568_p2 = ($signed(sext_ln73_fu_552_p1) + $signed(sext_ln73_267_fu_564_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = ($signed(sext_ln58_3229_fu_671_p1) + $signed(sext_ln58_3223_fu_614_p1));

assign grp_fu_293_p4 = {{grp_fu_210_p2[29:10]}};

assign grp_fu_303_p1 = grp_fu_210_p2;

assign grp_fu_303_p4 = {{grp_fu_303_p1[27:10]}};

assign grp_fu_313_p1 = grp_fu_210_p2;

assign sext_ln58_3217_fu_373_p1 = $signed(add_ln58_reg_681);

assign sext_ln58_3218_fu_382_p1 = $signed(add_ln58_4800_fu_376_p2);

assign sext_ln58_3219_fu_434_p1 = $signed(add_ln58_4801_reg_686);

assign sext_ln58_3220_fu_437_p1 = $signed(add_ln58_4802_reg_691);

assign sext_ln58_3221_fu_446_p1 = $signed(add_ln58_4803_fu_440_p2);

assign sext_ln58_3222_fu_456_p1 = $signed(add_ln58_4804_fu_450_p2);

assign sext_ln58_3223_fu_614_p1 = $signed(add_ln58_4805_reg_696);

assign sext_ln58_3224_fu_623_p1 = $signed(add_ln58_4806_fu_617_p2);

assign sext_ln58_3225_fu_627_p1 = $signed(add_ln58_4807_reg_706);

assign sext_ln58_3226_fu_636_p1 = $signed(add_ln58_4809_reg_711);

assign sext_ln58_3227_fu_645_p1 = $signed(add_ln58_4810_fu_639_p2);

assign sext_ln58_3228_fu_661_p1 = $signed(add_ln58_4812_fu_655_p2);

assign sext_ln58_3229_fu_671_p1 = $signed(add_ln58_4813_fu_665_p2);

assign sext_ln58_fu_610_p1 = $signed(trunc_ln42_14_fu_600_p4);

assign sext_ln70_465_fu_340_p1 = $signed(ap_port_reg_data_1_val);

assign sext_ln70_466_fu_355_p1 = $signed(ap_port_reg_data_2_val);

assign sext_ln70_467_fu_364_p1 = $signed(ap_port_reg_data_3_val);

assign sext_ln70_468_fu_392_p1 = $signed(ap_port_reg_data_4_val);

assign sext_ln70_469_fu_401_p1 = $signed(ap_port_reg_data_5_val);

assign sext_ln70_470_fu_416_p1 = $signed(ap_port_reg_data_6_val);

assign sext_ln70_471_fu_425_p1 = $signed(ap_port_reg_data_7_val);

assign sext_ln70_472_fu_466_p1 = $signed(ap_port_reg_data_9_val);

assign sext_ln70_473_fu_481_p1 = $signed(ap_port_reg_data_10_val);

assign sext_ln70_474_fu_490_p1 = $signed(ap_port_reg_data_11_val);

assign sext_ln70_475_fu_505_p1 = $signed(ap_port_reg_data_12_val);

assign sext_ln70_476_fu_514_p1 = $signed(ap_port_reg_data_13_val);

assign sext_ln70_477_fu_539_p1 = $signed(ap_port_reg_data_14_val);

assign sext_ln70_478_fu_595_p1 = $signed(ap_port_reg_data_15_val);

assign sext_ln70_479_fu_336_p1 = $signed(reg_323);

assign sext_ln70_480_fu_345_p1 = $signed(grp_fu_303_p4);

assign sext_ln70_481_fu_360_p1 = $signed(reg_323);

assign sext_ln70_482_fu_369_p1 = $signed(grp_fu_303_p4);

assign sext_ln70_483_fu_397_p1 = $signed(reg_327);

assign sext_ln70_484_fu_406_p1 = $signed(grp_fu_293_p4);

assign sext_ln70_485_fu_421_p1 = $signed(reg_323);

assign sext_ln70_486_fu_430_p1 = $signed(grp_fu_293_p4);

assign sext_ln70_487_fu_584_p1 = $signed(trunc_ln42_7_fu_574_p4);

assign sext_ln70_488_fu_588_p1 = $signed(trunc_ln42_8_reg_701);

assign sext_ln70_489_fu_486_p1 = $signed(reg_327);

assign sext_ln70_490_fu_495_p1 = $signed(grp_fu_293_p4);

assign sext_ln70_491_fu_510_p1 = $signed(reg_327);

assign sext_ln70_492_fu_529_p1 = $signed(trunc_ln42_12_fu_519_p4);

assign sext_ln70_493_fu_591_p1 = $signed(reg_323);

assign sext_ln70_fu_331_p1 = $signed(data_0_val);

assign sext_ln73_267_fu_564_p1 = $signed(shl_ln73_s_fu_556_p3);

assign sext_ln73_fu_552_p1 = $signed(shl_ln_fu_544_p3);

assign shl_ln73_s_fu_556_p3 = {{ap_port_reg_data_8_val}, {6'd0}};

assign shl_ln_fu_544_p3 = {{ap_port_reg_data_8_val}, {12'd0}};

assign trunc_ln42_12_fu_519_p1 = grp_fu_210_p2;

assign trunc_ln42_12_fu_519_p4 = {{trunc_ln42_12_fu_519_p1[24:10]}};

assign trunc_ln42_14_fu_600_p1 = grp_fu_210_p2;

assign trunc_ln42_14_fu_600_p4 = {{trunc_ln42_14_fu_600_p1[25:10]}};

assign trunc_ln42_7_fu_574_p4 = {{add_ln73_fu_568_p2[28:10]}};

assign trunc_ln42_8_fu_471_p1 = grp_fu_210_p2;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_32_18_5_3_0_config8_s
